project_id = "kobnxoultplzcdxiaeqo"

[functions.create-asset]
verify_jwt = false

[functions.ingest-asset]
verify_jwt = false

[functions.generate-blueprint]
verify_jwt = false

[functions.generate-final-video]
verify_jwt = false

[functions.generate-base-image]
verify_jwt = false
